name: Detect Selector Changes

on:
  push:
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
      - '**/*.jsx'

jobs:
  detect_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Python dependencies
        run: pip install beautifulsoup4 openai requests

      - name: Run selector diff script
        run: python .github/scripts/diff_selectors.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OBSERVEPOINT_API_KEY: ${{ secrets.OBSERVEPOINT_API_KEY }}
